# Generated by Django 5.2.4 on 2025-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth', '0002_room_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
